name: nlp-workshop
channels:
  - derickl
  - conda-forge
dependencies:
  - python>=3.7
  - pandas
  - numpy
  - flask
  - jsonnet
  - jupyterlab
  - ipywidgets
  - nodejs
  - ujson
  - pip
  - pip:
    - fire
    - torch>=1.0.0
    - torchvision
    - fastai>=1.0
    - allennlp
    - seaborn
    - sentencepiece
    - spacy
    - aiogram
    - tqdm 
    - redis
    - praw>=6.1.1
    - python-dotenv
    - docker-compose